// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdfuwnaromckloteeomp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZnV3bmFyb21ja2xvdGVlb21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDM4NTgsImV4cCI6MjA3MTE3OTg1OH0.sI9yEEykn9skeYw1TyiZGEfWVz1w3iSgn2Rm6GwPB-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});